### ISSUE TITLE
ModuleNotFoundError: No module named 'geometry_msgs'

### ISSUE THREAD

**Issue by AlphaGoLzh** [gkahn13/badgr#29]
I think I strictly followed the operation written in the README, and when the execution reached the Evaluation stage, when I ran `python scripts/eval.py configs/bumpy_collision_position.py` of code, an error was reported:
```
FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lizehao/anaconda3/envs/badgr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lizehao/anaconda3/envs/badgr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lizehao/anaconda3/envs/badgr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/lizehao/anaconda3/envs/badgr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/lizehao/anaconda3/envs/badgr/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "scripts/eval.py", line 22, in <module>
    params = import_config(config_fname)
  File "/mnt/c/Users/LZH/Desktop/badgr/src/badgr/utils/python_utils.py", line 15, in import_config
    spec.loader.exec_module(config)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/users/lzh/desktop/badgr/configs/bumpy_collision_position.py", line 6, in <module>
    from badgr.jackal.envs.jackal_env import JackalEnv
  File "/mnt/c/Users/LZH/Desktop/badgr/src/badgr/jackal/envs/jackal_env.py", line 11, in <module>
    from geometry_msgs.msg import Pose2D
ModuleNotFoundError: No module named 'geometry_msgs'
```

How can I fix it?

**Comment by 931011** [comment]
Hello, has it been solved?

**Comment by ChenxuWen-hub** [comment]
Excuse me, has it been resolved? I encountered the error 404 when accessing the dataset download link https://drive.google.com/drive/folders/1zjtuqMIfgEbKTZ-H-uHqCKS8RPDoYiwc?usp=sharing. Could you please provide the data?

**Comment by AlphaGoLzh** [comment]
Sorry, the dataset I currently have is only BADGR_rosbags.zip, and it doesn't seem to be complete.




云中谁忆
***@***.***
